version: '3'

services:

  csgo:
    image: cm2network/csgo
    container_name: csgo-server
    network_mode: host
    environment:
      - SRCDS_TOKEN=${CSGO_TOKEN}
      - SRCDS_RCONPW=${CSGO_RCONPW} 
      - SRCDS_PW=${CSGO_SERVERPW}
      - SRCDS_PORT=27015
      - SRCDS_TV_PORT=27020
      - SRCDS_FPSMAX=300
      - SRCDS_TICKRATE=128
      - SRCDS_MAXPLAYERS=${CSGO_MAXPLAYERS}
      - SRCDS_STARTMAP=${CSGO_STARTMAP}
      - SRCDS_REGION=3
      - SRCDS_MAPGROUP="mg_active"

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=${TZ}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
    volumes:
      - /home/centos/duckdns/config:/config #optional
    restart: unless-stopped
